In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("ecommerce_sales.csv")

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [5]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
376087,569493,23202,JUMBO BAG VINTAGE LEAF,10,10/4/2011 13:35,2.08,13317.0,United Kingdom
376088,569493,23254,CHILDRENS CUTLERY DOLLY GIRL,4,10/4/2011 13:35,4.15,13317.0,United Kingdom
376089,569493,22780,LIGHT GARLAND BUTTERFILES PINK,4,10/4/2011 13:35,4.25,13317.0,United Kingdom
376090,569493,22779,WOODEN OWLS LIGHT GARLAND,4,10/4/2011 13:35,4.25,13317.0,United Kingdom
376091,569493,22741,FUNKY DIVA PEN,48,10/4/2011 13:35,0.85,13317.0,United Ki

In [7]:
df.shape

(376092, 8)

In [8]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [9]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376092 entries, 0 to 376091
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    376092 non-null  object
 1   StockCode    376092 non-null  object
 2   Description  374819 non-null  object
 3   Quantity     376092 non-null  int64
 4   InvoiceDate  376092 non-null  object
 5   UnitPrice    376092 non-null  float64
 6   CustomerID   277315 non-null  float64
 7   Country      376092 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 23.0+ MB

In [11]:
df.describe()
#Description #CustomerID

            Quantity      UnitPrice     CustomerID
count  376092.000000  376092.000000  277315.000000
mean        9.800618       4.774822   15278.890933
std       180.268614     106.348714    1715.264076
min    -74215.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13881.000000
50%         3.000000       2.100000   15150.000000
75%        10.000000       4.130000   16782.000000
max     74215.000000   38970.000000   18287.000000